## Pytorch Basic Fundamentals

In [1]:
import torch

randint = torch.randint(-100, 100, (5,))
randint

tensor([  8,  63, -54,  -4,  30])

In [ ]:
tensor = torch.rand(3, 2)
tensor

tensor([[0.8225, 0.9045],
        [0.2724, 0.7028],
        [0.6283, 0.7486]])

In [5]:
zeros = torch.zeros(3,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
ones = torch.ones(4,2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
input = torch.empty(2, 3)
input

tensor([[1.0801e-05, 2.0773e+20, 1.9971e+20],
        [1.0017e-11, 2.1156e+23, 2.1764e-04]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
# constant 5 increment from 3 to 10
line_space = torch.linspace(3, 10, steps=5)
line_space

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
log_space = torch.logspace(start=-10, end=10, steps=5)
log_space

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
# Diagonal Line
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
a = torch.empty((2,3), dtype=torch.int32)
empty_list = torch.empty_like(a)
empty_list


tensor([[         0,          0, 1350192304],
        [     24515, 1861753168,      31912]], dtype=torch.int32)

### Diving more into Fundamentals

In [3]:
import torch 

prob = torch.tensor([0.1, 0.9])
# 10% or 0.1-> index 0
# 90% or 0.9-> index 1
# each probability points to the index of the probaility in the tensor
samples = torch.multinomial(prob, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 1, 1, 0, 1, 1])


In [ ]:
tensor1 = torch.arange(1, 5)
tensor2 = torch.arange(5, 9)
print(tensor1, tensor2, sep="\n")

# concat the new predictions with predicted old tensors(characters)
out = torch.cat((tensor1, tensor2))
print(out, out.dim(), sep="\n")

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
1


In [ ]:
# Autoregressive -> predict new tokens based on prev tokens
# Triangle Lower
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# Triangle Upper
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# exponent of -inf = 0
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5))==0, float("-inf"))
out

tensor([[0.0000, 3.1416, 3.1416, 3.1416, 3.1416],
        [0.0000, 0.0000, 3.1416, 3.1416, 3.1416],
        [0.0000, 0.0000, 0.0000, 3.1416, 3.1416],
        [0.0000, 0.0000, 0.0000, 0.0000, 3.1416],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])